#                                                                 -*- ruby -*-
require 'rubygems'
require 'jekyll-helpers'

include JekyllHelpers

CSS_DIR  = "../tmp/css"
LESS_DIR = "../tmp/less"
COMPRESS = true

JekyllHelpers::Tasks.new.install do |config|
  config.less_dir      = LESS_DIR
  config.css_dir       = CSS_DIR
  config.less_compress = COMPRESS
end

task :dummy

task :run => 'jekyll_helpers:watch_less' do
  Process.wait
end
